name: mindspore-docker-cd
on:
  push:
    branches:
      - main
    paths:
      - "docker_images/mindspore/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c  # v4
        with:
          python-version: "3.10"
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480  # v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9  # v1
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install awscli
      - uses: huggingface/tailscale-action@ee9ee9c497b1088140a77088ee948ed0bc91f9d0  # v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Update upstream
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          DEFAULT_HOSTNAME: ${{ secrets.DEFAULT_HOSTNAME }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          python build_docker.py mindspore --out out.txt
      - name: Deploy on API
        run: |
          # Load the tags into the env
          cat out.txt >> $GITHUB_ENV
          export $(xargs < out.txt)
          echo ${MINDSPORE_CPU_TAG}
          # Weird single quote escape mechanism because string interpolation does
          # not work on single quote in bash
          curl  -H "Authorization: Bearer  ${{ secrets.API_GITHUB_TOKEN }}"   https://api.github.com/repos/huggingface/api-inference/actions/workflows/update_community.yaml/dispatches   -d '{"ref":"main","inputs":{"framework":"MINDSPORE","tag": "'"${MINDSPORE_CPU_TAG}"'"}}'
